// Common alternate names, anglicizations, and historic spellings that map to
// the canonical city name we expect to find in CDP disclosure data. Keys are
// lowercase, punctuation-stripped; consumers should normalize the search query
// the same way before lookup.
export const SEARCH_ALIASES: Record<string, string> = {
  nyc: 'new york',
  'new york city': 'new york',
  la: 'los angeles',
  sf: 'san francisco',
  philly: 'philadelphia',
  vegas: 'las vegas',
  nola: 'new orleans',
  dc: 'district of columbia dc',
  'd c': 'district of columbia dc',
  'washington dc': 'district of columbia dc',
  'the twin cities': 'metropolitan council twin cities',
  'minneapolis st paul': 'metropolitan council twin cities',
  'minneapolis saint paul': 'metropolitan council twin cities',
  'easter island': 'rapa nui isla de pascua',
  'isla de pascua': 'rapa nui isla de pascua',
  bombay: 'mumbai',
  madras: 'chennai',
  calcutta: 'kolkata',
  bangalore: 'bengaluru',
  mysore: 'mysuru',
  trivandrum: 'thiruvananthapuram',
  cochin: 'kochi',
  pondicherry: 'puducherry',
  gurgaon: 'gurugram',
  peking: 'beijing',
  canton: 'guangzhou',
  amoy: 'xiamen',
  tientsin: 'tianjin',
  chungking: 'chongqing',
  nanking: 'nanjing',
  hangchow: 'hangzhou',
  tsingtao: 'qingdao',
  sian: 'xian',
  saigon: 'ho chi minh city',
  hcmc: 'ho chi minh city',
  'ho chi minh': 'ho chi minh city',
  rangoon: 'yangon',
  leningrad: 'saint petersburg',
  petrograd: 'saint petersburg',
  stalingrad: 'volgograd',
  constantinople: 'istanbul',
  byzantium: 'istanbul',
  edo: 'tokyo',
  batavia: 'jakarta',
  djakarta: 'jakarta',
  salisbury: 'harare',
  'lourenco marques': 'maputo',
  leopoldville: 'kinshasa',
  elisabethville: 'lubumbashi',
  danzig: 'gdansk',
  breslau: 'wroclaw',
  konigsberg: 'kaliningrad',
  lemberg: 'lviv',
  lwow: 'lviv',
  kiev: 'kyiv',
  tiflis: 'tbilisi',
  kishinev: 'chisinau',
  salonika: 'thessaloniki',
  abo: 'turku',
  pusan: 'busan',
  munchen: 'munich',
  koln: 'cologne',
  nurnberg: 'nuremberg',
  wien: 'vienna',
  bruxelles: 'brussels',
  brussel: 'brussels',
  antwerpen: 'antwerp',
  'den haag': 'the hague',
  's gravenhage': 'the hague',
  roma: 'rome',
  milano: 'milan',
  firenze: 'florence',
  venezia: 'venice',
  napoli: 'naples',
  torino: 'turin',
  genova: 'genoa',
  livorno: 'leghorn',
  lisboa: 'lisbon',
  sevilla: 'seville',
  zaragoza: 'saragossa',
  praha: 'prague',
  warszawa: 'warsaw',
  moskva: 'moscow',
  beograd: 'belgrade',
  bucuresti: 'bucharest',
  athina: 'athens',
  kobenhavn: 'copenhagen',
  kjobenhavn: 'copenhagen',
  helsingfors: 'helsinki',
  geneve: 'geneva',
  genf: 'geneva',
  ginevra: 'geneva',
  bale: 'basel',
  'al qahirah': 'cairo',
  iskandariyah: 'alexandria',
  'ad dawhah': 'doha',
  'abu zaby': 'abu dhabi',
  dubayy: 'dubai',
  'al kuwayt': 'kuwait city',
  'ar riyad': 'riyadh',
  makkah: 'mecca',
  'al madinah': 'medina',
  yerushalayim: 'jerusalem',
  'al quds': 'jerusalem',
  bayrut: 'beirut',
  dimashq: 'damascus',
  halab: 'aleppo',
  tahran: 'tehran',
  esfahan: 'isfahan',
  'ad dar al bayda': 'casablanca',
  marrakech: 'marrakesh',
  'al jazair': 'algiers',
  tarabulus: 'tripoli',
  kl: 'kuala lumpur',
  hk: 'hong kong',
  macao: 'macau',
  'krung thep': 'bangkok',
  'ha noi': 'hanoi',
  'ciudad de mexico': 'mexico city',
  'mexico df': 'mexico city',
  df: 'mexico city',
  cdmx: 'mexico city',
  'ciudad de guatemala': 'guatemala city',
  'ciudad de panama': 'panama city',
  'la habana': 'havana',
  rio: 'rio de janeiro',
  'santiago de chile': 'santiago',
  'bogota dc': 'bogota',
  'baile atha cliath': 'dublin',
};

// Country-level aliases that map to the canonical CDP `discloser_country_or_area`
// value (normalized: lowercase, commas/parentheses stripped). Keep separate from
// SEARCH_ALIASES so callers can pick the right lookup for the field being matched.
export const COUNTRY_ALIASES: Record<string, string> = {
  usa: 'united states of america',
  'u s a': 'united states of america',
  us: 'united states of america',
  'u s': 'united states of america',
  'united states': 'united states of america',
  america: 'united states of america',
  states: 'united states of america',
  uk: 'united kingdom',
  'u k': 'united kingdom',
  britain: 'united kingdom',
  'great britain': 'united kingdom',
  gb: 'united kingdom',
  england: 'united kingdom',
  scotland: 'united kingdom',
  wales: 'united kingdom',
  'northern ireland': 'united kingdom',
  uae: 'united arab emirates',
  emirates: 'united arab emirates',
  korea: 'korea the republic of',
  'south korea': 'korea the republic of',
  'republic of korea': 'korea the republic of',
  'korea republic of': 'korea the republic of',
  vietnam: 'viet nam',
  turkey: 'turkiye',
  'czech republic': 'czechia',
  czechoslovakia: 'czechia',
  holland: 'netherlands kingdom of the',
  netherlands: 'netherlands kingdom of the',
  'the netherlands': 'netherlands kingdom of the',
  venezuela: 'venezuela bolivarian republic of',
  'bolivarian republic of venezuela': 'venezuela bolivarian republic of',
  drc: 'democratic republic of the congo',
  'dr congo': 'democratic republic of the congo',
  'dr of the congo': 'democratic republic of the congo',
  'congo kinshasa': 'democratic republic of the congo',
  'congo drc': 'democratic republic of the congo',
  zaire: 'democratic republic of the congo',
  'ivory coast': 'cote divoire',
  taiwan: 'taiwan greater china',
  'republic of china': 'taiwan greater china',
  'chinese taipei': 'taiwan greater china',
  'hong kong': 'china hong kong special administrative region',
  hk: 'china hong kong special administrative region',
  'hong kong sar': 'china hong kong special administrative region',
  prc: 'china',
  'peoples republic of china': 'china',
  'mainland china': 'china',
  bosnia: 'bosnia and herzegovina',
  herzegovina: 'bosnia and herzegovina',
  'uruguay oriental': 'uruguay',
};
