export const environment = {
  production: true,
  baseUrl: '',
  aiServerUrl: 'https://cdp-ai-server-pbybuiwoxq-uc.a.run.app',
  aiModel: 'cdp-gemini',
  apiKey: '',
  apiKeyHeaderName: 'X-API-Key',
  aiServerApiKey: '',
  aiServerApiKeyHeaderName: 'X-API-Key',
  authDisabled: false,
  isDebugMode: false,
  firebaseConfig: {
    apiKey: '',
    authDomain: '',
    projectId: '',
    storageBucket: '',
    messagingSenderId: '',
    appId: '',
    measurementId: '',
  },
  mapsConfig: {
    apiKey: '',
  },
  posthog: {
    key: '',
    host: 'https://eu.i.posthog.com',
    enabled: false,
  },
  sentry: {
    dsn: '',
    enabled: false,
    environment: 'development',
    release: '',
    tracesSampleRate: 0.05,
  },
};
